In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [ ]:
np.__version__

'1.21.6'

# creating array using python list using numpy

In [2]:
a = np.array([1,2,3])

In [3]:
type(a)

numpy.ndarray

In [ ]:
a

array([1, 2, 3])

In [ ]:
list1 = [True, 55, "kshitiz"]

In [ ]:
list1

[True, 55, 'kshitiz']

In [ ]:
type(list1[0])

bool

In [ ]:
arr = np.array([True, 55, "kshitiz"])

In [ ]:
arr

array(['True', '55', 'kshitiz'], dtype='<U21')

In [ ]:
arr[0]

'True'

In [ ]:
type(arr[0])

numpy.str_

# How to create an array? -- use `np.array()`

In [ ]:
import numpy as np

a = np.array([7,44,1])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.ndim

1

In [ ]:
a.shape

(3,)

In [ ]:
a = np.array([7,44,1])
array1 = a.reshape(-1,1)
array1

array([[ 7],
       [44],
       [ 1]])

In [ ]:
array1.shape

(3, 1)

In [ ]:
array1.ndim

2

In [ ]:
array2 = a.reshape(1,-1)
array2

array([[ 7, 44,  1]])

In [ ]:
array2.shape

(1, 3)

In [ ]:
array2.ndim

2



The criterion to satisfy for providing the new shape is that 'The new shape should be compatible with the original shape'

numpy allow us to give one of new shape parameter as -1 (eg: (2,-1) or (-1,3) but not (-1, -1)). It simply means that it is an unknown dimension and we want numpy to figure it out. And numpy will figure this by looking at the 'length of the array and remaining dimensions' and making sure it satisfies the above mentioned criteria

# Generating numpy array

* ones()
* zeros()

* empty()

In [ ]:
import numpy as np

In [ ]:
np.ones(6, dtype = np.int8)

array([1, 1, 1, 1, 1, 1], dtype=int8)

In [ ]:
np.ones(6, dtype=np.int16)

array([1, 1, 1, 1, 1, 1], dtype=int16)

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.zeros(4).shape

(4,)

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,3)).shape

(3, 3)

In [ ]:
np.zeros(9).reshape(3,-1)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.empty(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# You can create an array with range of elements using `np.arange()`

In [ ]:
list(range(1,10, 1))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,6,2)

array([1, 3, 5])

In [ ]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

# use `np.linspace()` to create array with values that are spaced linearly in a specified interval

In [ ]:
np.linspace(0, 0.5, 6)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5])

In [ ]:
# np.linspace(0, 10, 10)

# concat  and sorting two numpy array

In [ ]:
arr = np.array([-1,-11,4,77,2,-99,3])

In [ ]:
np.sort(arr) # assignment des order

array([-99, -11,  -1,   2,   3,   4,  77])

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [ ]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a + b

array([ 6,  8, 10, 12])

# indexing in numpy array

In [ ]:
a = np.arange(1,6)

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
a[0]

1

In [ ]:
a[3]

4

In [ ]:
a[2:4]

array([3, 4])

In [ ]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [ ]:
a[[1,3,4]] # fancy indexing in numpy

array([2, 4, 5])

In [ ]:
a = np.arange(1,6)

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
a[2:4] = 0

In [ ]:
a

array([1, 2, 0, 0, 5])

In [ ]:
a[-2] # negative indexing

0

# `np.any() , np.all()`


<img src = "https://miro.medium.com/max/1100/1*nFGcXav_xxD7TXGiRYMpHg.png">

In [ ]:
a = np.array([1,2,3,4,5,6,7,6,5,4,3,2,1])

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
a > 5

array([False, False, False, False, False,  True,  True,  True, False,
       False, False, False, False])

In [ ]:
np.any(a>5)

True

In [ ]:
np.all(a>5)

False

In [ ]:
a[a>5]

array([6, 7, 6])

In [ ]:
# assignment  & | ^ ~ : Python Bitwise Operators

# vector operation in numpy array

In [ ]:
a = np.array([1,2])
b = np.array([4,8])

In [ ]:
a + b

array([ 5, 10])

In [ ]:
a - b

array([-3, -6])

In [ ]:
a * b

array([ 4, 16])

In [ ]:
a / b

array([0.25, 0.25])

In [ ]:
a = np.array([1,2])
b = np.array([4,8])
a  ** b

array([  1, 256])

# Broadcasting in numpy array


In [ ]:
a = np.array([1,2])

In [ ]:
a + 3 # broadcasting -- used brightness and contrast adjustment in image processing

array([4, 5])

In [ ]:
a - 3

array([-2, -1])

# array operaton

* np.floor()
* np.ceil()
* np.round()

In [4]:
a = np.array([1.132,1.549, 1.919, 2.571])

In [5]:
np.floor(a)

array([1., 1., 1., 2.])

In [6]:
np.ceil(a)

array([2., 2., 2., 3.])

In [7]:
np.round(a, decimals = 2)

array([1.13, 1.55, 1.92, 2.57])

# statistics using numpy

In [8]:
a = np.array([44,33,66])

In [9]:
a.max()

66

In [10]:
a.min()

33

In [11]:
a.argmax()

2

In [12]:
a.argmin()

1

In [13]:
a.sum()

143

In [14]:
a.std()

13.719410418171117

In [15]:
a.var()

188.2222222222222

In [16]:
round(a.mean(), 2)

47.67